export const DEFAULT_SAW_KERF = 3;       // mm
export const DEFAULT_FRESH_EDGE_TRIM = 10; // mm per side
export const MIN_OFFCUT_AREA = 10000;     // mm² (~100×100mm) to be considered reusable
export const OFFCUT_STOCK_KEY = 'rozkroj_offcuts';
export const DARK_MODE_KEY = 'rozkroj_dark_mode';
export const LAST_UNIT_KEY = 'rozkroj_last_unit';
export const DEFAULT_MATERIAL_NAME = 'Chipboard 18mm';
export const DEFAULT_EDGE_BANDING = { top: false, right: false, bottom: false, left: false };
export const UNSAVED_CHANGES_CONFIRM_MESSAGE = 'You have unsaved changes that will be lost. Continue?';
